Repository TheTypingMatch/lecashbot, pull requests merged in 2020-06, with the labels that each got.

#51 Fixing cost/reward for next flip
  src/commands/coinflip.ts
Labels: commands, high priority, type: bug/fix

#52 Fixed Grammatical Errors
  src/commands/register.ts
  src/config/embeds.ts
Labels: priority: low, type: refactor

#54 Lost streak message
  src/commands/coinflip.ts
  src/commands/register.ts
  src/config/embeds.ts
Labels: priority: low, type: enhancement
